### ISSUE TITLE
Develop Guidance on Building and Managing Contributor Communities

### ISSUE THREAD

**Issue by smbuthia** [WorldHealthOrganization/open-source-communication-channel#45]
Leveraging communities of contributors is a key part of managing open source projects. To do this, project teams need to provide platforms and channels through which these communities can share ideas, ask questions, and interact.  The guidance on building and managing contributor communities is to support teams trying to figure out:

- [ ] what contributor community forum platforms to use,
- [ ] how to go about developer and contributor advocacy,
- [ ] planning and facilitating contributor community events, and more

**Comment by ihuman56** [comment]
Hello @smbuthia I learned about the WHO project through a discussion at an OSPO event and after reading the project's contributing instructions and readme. I find this topic to be interesting, and I'd love to know if the public is welcome to participate since I'd love to contribute.

**Comment by smbuthia** [comment]
Hi @ihuman56! Thank you for your interest in the WHO OSPO. 

Like many open innovations and open source projects, anyone with something to contribute can be a part of this community. A few quick ways are:

- start a [discussion](https://github.com/WorldHealthOrganization/open-source-communication-channel/discussions) in any one of the categories,
- open a [new issue](https://github.com/WorldHealthOrganization/open-source-communication-channel/issues/new/choose) with proposed improvements to the guidelines we are creating, or
- comment on an existing issue (like this one) with suggestions and ideas

We welcome your contributions and look forward to collaborating!
