### ISSUE TITLE
Document WHO Open Source Strategy

### ISSUE THREAD

**Issue by smbuthia** [WorldHealthOrganization/open-source-communication-channel#57]
As we continue to formalize the World Health Organization's approach to open source management and strategy, we are documenting the strategy that will guide the adoption and development of open source. This document will:

- elaborate on WHO's approach to open source and support of its use,
- highlight strategies on the consumption of open source,
- support the WHO's contribution to open source projects,
- provide high level guidance for licenses, policies, and procurement templates (deeper, more detailed guidance will exist separately),
- define a usage policy and trademark, and more

_EDIT:_
Further elaborating on the efforts here, below is a breakdown of activities to accomplish this work:
- [x] Form a working group to develop the open source strategy
- [x] Develop a draft of the strategy with an intuitive flow and covering critical open source areas
- [ ] Share the draft for review with a wider audience representing 3 levels (country, region, and HQ)
- [ ] Incorporate feedback from review
- [ ] Share strategy with higher level leadership team for review and approval
- [ ] Incorporate feedback from final review and get final approval
- [ ] Launch the open source strategy and disseminate it through official channels

**Comment by smbuthia** [comment]
Further elaborating on the efforts here, below is a breakdown of activities to accomplish this work:
- [x] Form a working group to develop the open source strategy
- [ ] Develop a draft of the strategy with an intuitive flow and covering critical open source areas
- [ ] Share the draft for review with a wider audience representing 3 levels (country, region, and HQ)
- [ ] Incorporate feedback from review
- [ ] Share strategy with higher level leadership team for review and approval
- [ ] Incorporate feedback from final review and get final approval
- [ ] Launch the open source strategy and disseminate it through official channels
